- src/app.js
- src/models/Prueba.js
- src/routes/category.js
- src/routes/products.js
Add the initial files for routes to master
> Develop to master

- src/models/Product.js
> corregir nombre Product

- src/routes/products.js
> ruta delete de product

- src/routes/products.js
ajustes para encontrar todos los productos o los que contengan la query.
> ajustes en la ruta get de productos

- src/routes/products.js
se corrigio ruta delete y ruta get by id
> Ruta deletee

- src/routes/category.js
rutas Post y Delete a CATEGORY, ambas están funcionando, faltan rutas get (/,/:id,/:name)
> rutas post y delete category

- src/routes/category.js
Ruta get category all y por name
> ruta get todo y por nombre

- src/routes/category.js
- src/routes/products.js
se agrego la relacion del producto con la categoria en la ruta post. Solo eso, podrian aparecer mas lineas cambiadas. Pero solo se modifico eso.
> se agrego a ruta post  la relacion con la categoria

- index.js
- src/routes/category.js
- src/routes/products.js
> ruta PUT product

- src/models/Product.js
- src/routes/category.js
Agrege un validator en el modelo Products al dato Price, ya que si le ponia como valor una letra lo tomaba como valido y creaba el producto.
Tambien agregue un lowerCase en la ruta get de category, ya que si se buscaba por query el producto con mayusculas/minusculas distinto a como se creo tiraba error.
> agrege validacion a price y lowercase en category

- index.js
- src/models/Order.js
- src/models/User.js
- src/routes/products.js
> Fede models

- src/models/User.js
> corrijo password doble

- src/routes/products.js
> ajustes en el get de productos

- src/app.js
- src/db.js
- src/models/Review.js
- src/routes/review.js
> Model ruta review

- src/routes/products.js
Mostrar review en la ruta productId
> ruta productId Ajuste para que muestre los review

- index.js
- src/app.js
- src/db.js
- src/routes/order.js
- src/routes/user.js
Chicos, hice todo de una. La dinamica va lenta y bueno, tuve tiempo de ponerme con esto.
Hice creo que todas las rutas de carrito y modelos y relaciones. Anda todo, lo probe.
Ahora mando por whatsapp una lista con todas las rutas y lo que se necesita para cada una.
Hice las rutas de order a las cuales hay que agregarle lo que corresponda de pasarela de pago, e mail, autenticacion y demas...
Es largo pero aproveche,,, esta todo chequeado, ahora hay que adpatar el front a estas rutas.
> rutas user, cart, order

- src/models/User.js
para que no se caiga el server, vemos como lo acomodamos....
> cambie enum a string por ahora

- src/app.js
- src/routes/payment.js
- src/routes/stripe.js
recibe la señal faile o success de stripe para modificar el estado de la orden.
> recibir un post de stripe

- src/app.js
corregir develop con lineas duplicadas.
> correcion en develop

- src/routes/payment.js
recibir el user id para calcular el pago
> recibir el userId para calcular el pago

- src/routes/payment.js
- src/routes/stripe.js
- src/routes/user.js
configuración de función precio final
> configuración de función precio final

- src/routes/payment.js
- src/routes/stripe.js
> ajustes pasarela de pago

- src/routes/payment.js
- src/routes/stripe.js
- src/routes/user.js
> ajuste de pagos

- src/routes/payment.js
> validacion de payment

- src/app.js
- src/db.js
- src/models/Image.js
- src/routes/image.js
> modelo de imagen

- src/routes/payment.js
> ruta de payment para modificar el stock del producto
